<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-colors-flat.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
<HTML>
<HEAD>
<TITLE>SCU Businesses Directory</TITLE>
<style>
h1{
    font-family: 'Prata', serif;
color: #FFFFFF;
    background-color: #72001B;
}
h3{
    color: #72001B;
}
h5{
    color: #72001B;
}
</style>
</HEAD>

<div id="id03" class="w3-modal">
    <div class="w3-modal-content w3-animate-top w3-card-4">
        <header class="w3-container w3-flat-pomegranate">
        <span onclick="document.getElementById('id03').style.display='none'"
        class="w3-button w3-display-topright">&times;</span>
        <h2>Access Denied</h2>
        </header>
    </div>
</div>

<body onload= "PopCheck()" >
<script>
    function PopCheck(){
        if(sessionStorage.getItem("correctPassword") != true){
            document.getElementById('id03').style.display='block'
        
        }
    }
</script>


<div Align =left> <a href="index.php" class="w3-button w3-black">Back to directory</a></div>
<div Align =left> <a href="users.php" class="w3-button w3-black">View Users</a></div>
<div class="w3-container">
<h1 ALIGN=CENTER>Alumni Office Admin Page
</h1>
</div>
</div>

<?php
	include 'functions.php';
	if(!empty($_POST["DeleteName"])){
	    removeListingAdmin($_POST["DeleteName"]);
	}
	if(!empty($_POST["ApproveName"])){
	    approveListing($_POST["ApproveName"]);
	}
	if(!empty($_POST["EditName"])){
		editListing($_POST["EditName"]);
	}
?>

<div class="w3-container">
	<div class="w3-quarter">
        <div class="w3-twothird">
            <div class="w3-container w3-light-grey w3-justify">
                <h3>Remove Listing </h3>
                <form action="AlumniOffice.php" method = "post">
                Name <input type="text" name="DeleteName" value=""><br><br>
                <input type="submit" value="Remove">
                </form>
            </div>
			<br>
			<div class="w3-container w3-light-grey w3-justify">
				<h3>Approve Listing </h3>
				<form action="AlumniOffice.php" method = "post">
				Name <input type="text" name="ApproveName" value=""><br><br>
				<input type="submit" value="Approve">
				</form>
			</div>
			<br>
			<div class="w3-container w3-light-grey w3-justify">
				<h3>Approve Edit Request</h3>
				<form action="AlumniOffice.php" method = "post">
				Name <input type="text" name="EditName" value=""><br><br>
				<input type="submit" value="Approve">
				</form>
			</div>
        </div>
    </div>
    <?php
    getListingsAdmin();
    ?>
    
	<br>
</div>

<br>
<p>
<br>
Disclaimer: The content of these web pages is not generated by and does not represent the views of Santa Clara University or any of its departments or organizations.
</p>

</HTML>
