<HTML>
<HEAD>
<TITLE>Peter L Paulson's Web Page</TITLE>
</HEAD>

<BODY BGCOLOR="#ffffcc" TEXT="#000000" LINK="#ff0000" VLINK="#990033">

<br>
<?php
echo "This is a test of PHP."
?>
<br>

<H1 ALIGN=CENTER>Peter L Paulson's Web Page</H1>

This is Peter L Paulson's web page.  You can send mail to me at <A HREF="mailto:ppaulson@students.engr.scu.edu">ppaulson@students.engr.scu.edu</A>.

<HR COLOR="#990033">

<UL>
  <LI><A HREF="http://www.scu.edu">Santa Clara University</A>
  <LI><A HREF="http://www.engr.scu.edu">SCU School of Engineering</A>
  <LI><A HREF="http://www.dc.engr.scu.edu">SCU Engineering Design Center</A>
  <LI><A HREF="http://students.engr.scu.edu">Engineering Student Webpages</A>
</UL>

<HR COLOR="#990033">

The content of these web pages is not generated by and does not represent the views of Santa Clara University or any of its departments or organizations.

</BODY>
</HTML>
